### ISSUE TITLE
Code Beauty Path Path error

### ISSUE THREAD

**Issue by isjia** [happypeter/rails10#27]
http://happypeter.github.io/rails10/12_beauty.html 中，关于patch path的代码有问题：

patch 'issues' => 'issues#update'

应该是：patch 'issues/:id' => 'issues#update'

视频中的代码是正确地

**Comment by happypeter** [comment]
https://github.com/happypeter/rails10/commit/7df763cdbc9a428bc432296961b72eaae577ddce

修正了，多谢！
