### ISSUE TITLE
Code Beauty 建议补全update action的代码

### ISSUE THREAD

**Issue by isjia** [happypeter/rails10#28]
http://happypeter.github.io/rails10/12_beauty.html

issues controller中关于update方法的代码没有给出，建议加上
def update
    i = Issue.find(params[:id])
    i.update_attributes(issue_params)
    redirect_to :root
  end

**Comment by happypeter** [comment]
这个我觉得没有必要加了，并不是所有的 resource 都需要更新操作。

**Comment by happypeter** [comment]
https://github.com/happypeter/rails10/commit/7df763cdbc9a428bc432296961b72eaae577ddce

已经修正，thx

**Comment by happypeter** [comment]
也欢迎直接给我发 Pull Request
