### ISSUE TITLE
apt-get 一些包失败

### ISSUE THREAD

**Issue by happypeter** [happypeter/rails10#29]
```
sudo apt-get install -y git-core curl zlib1g-dev build-essential \
                     libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 \
                     libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common
```

文档链接给我一下
Leon  20:19:49
http://happypeter.github.io/rails10/02_getrails.html
happypeter  20:20:24
我自己跑一般试试，稍等
Leon  20:20:33
好的，麻烦老师了
happypeter  20:21:29
把你的报错信息贴一下吧
Leon  20:21:44
恩，我跑一下，稍等

**Comment by zltunes** [comment]
![m1j3v ae qif466xl295y5i](https://cloud.githubusercontent.com/assets/10128980/6687357/4a12f22c-cce5-11e4-8ad8-e2ea19479a2d.png)
如图，rbenv和openssl没问题，但执行rbenv install 2.1.2后一直build failed..

**Comment by zltunes** [comment]
我系统里自带的是 ruby 1.9.3p484
是不是必须删除原有的？

**Comment by happypeter** [comment]
这里有一个概念要明确，编译的时候需要 ssl 意思是需要 .so 库和对应的头文件，并不是你系统的 openssl 能用就一定也有这两个东西的。这是个通用的规律，不局限于 openssl 这一个包。

**Comment by happypeter** [comment]
不是。

**Comment by happypeter** [comment]
执行

```
dpkg -l|grep -i ssl
```

请把输出贴到这里

**Comment by zltunes** [comment]
![3v 3r0 8h yyji3st2f ut](https://cloud.githubusercontent.com/assets/10128980/6687453/1b1c45e4-cce6-11e4-822c-c9fc77786a15.png)

**Comment by happypeter** [comment]
我的输出

```
ii  libssl-dev:amd64                 1.0.1f-1ubuntu2.8             amd64        Secure Sockets Layer toolkit - development files

ii  libssl1.0.0:amd64                1.0.1f-1ubuntu2.8             amd64        Secure Sockets Layer toolkit - shared libraries
```

**Comment by happypeter** [comment]
其中一个是 .so 库文件，libssl-dev 中是头文件。

你的貌似没有 libssl-dev

**Comment by happypeter** [comment]
```
sudo apt-get install libssl-dev<tab>
```

装一下试试

**Comment by zltunes** [comment]
![e_omd0t94tdtov46cukt vf](https://cloud.githubusercontent.com/assets/10128980/6687577/1e64f132-cce7-11e4-930d-9c8b79fc4223.png)
出现了一开始安装那些库文件时报的错误，404Not Found

**Comment by happypeter** [comment]
我这边安装成功了，完全按照文档的步骤。

```
Installed ruby-2.1.2 to /home/vagrant/.rbenv/versions/2.1.2

vagrant@vagrant-ubuntu-trusty-64:~$ rbenv global 2.1.2
vagrant@vagrant-ubuntu-trusty-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
vagrant@vagrant-ubuntu-trusty-64:~$
```

**Comment by happypeter** [comment]
是 apt-get 又出了问题。我这边安装的  

```
libssl-dev:amd64                 1.0.1f-1ubuntu2.8 
```

注意上面的小版本是 2.8，而你那里却是去服务器上找 2.7

所以找不到是情有可原的。具体原因 ... 我看看...

**Comment by happypeter** [comment]
再执行一下

```
sudo apt-get update
```

然后再试试

不行的话那可能就没有办法了，就是你的系统有问题了，我原来是专门的包管理工程师，所以包管理系统出问题还是挺常见的，哈哈

这样，那就换我这个64位系统吧。你用的那个应该是32的镜像。http://happypeter.github.io/rails10/01_vagrant.html 这里的步骤操作就可以了

**Comment by zltunes** [comment]
![f_gnrq66zugeivy 3xbcj31](https://cloud.githubusercontent.com/assets/10128980/6687919/594a7dd2-ccea-11e4-8831-9921457085e0.png)
我的也是64位的。。心塞。。
我Ubuntu自带的是ruby1.9.3p484   我就用这个跟着您的课程做可以吗？

**Comment by happypeter** [comment]
不确定，可以试试。

建议可以用文档上的步骤再试一次，我刚才刚弄的，安装是可以成功的。

**Comment by zltunes** [comment]
好的，我再试试，非常感谢您！
