### ISSUE TITLE
ruby on rails 的网站怎么部署

### ISSUE THREAD

**Issue by happypeter** [happypeter/rails10#8]
> ruby on rails 的网站怎么部署？ 本机上调通了，如何找到便宜的服务器并做域名指向？haoqicat 是放在哪里的？

**Comment by happypeter** [comment]
http://happycasts.net/episodes/78
haoqicat 是放在 linode 东京的机房。上面的视频介绍了 rails 项目如何部署在 ubuntu 之上的步骤。

> 如何找到便宜的服务器并做域名指向？

这个问题基本的答案就是：
1. 到买域名的地方，例如 domain.com，把我们的域名指向 linode 的 DNS
2. 登陆我们的 linode 账户-> DNS Manager ->  add a domain zone 
3. 点开我们的一个域名，把各个 subdomain 指向我们自己的 linode VPS 就可以了，一般要等半个小时设置才生效
![screen shot 2013-11-30 at 10 30 38 am](https://f.cloud.github.com/assets/72467/1648028/b700e21a-5967-11e3-852c-81f8fe6e2690.png)

  注意：主要还是要有 `*` 这一条，下面那些不设也都能用。

**Comment by happypeter** [comment]
> 如何找到便宜的服务器

关于 aliyun: 域名必须备案才能使用，备案至少要两周时间，很麻烦。最低配的每个月 60 来块钱 RMB，但是跑 rails 项目很吃力。

国外的服务器都不用备案
- linode 稍稍贵一些，但是网速最快（尤其是东京节点），即使是最低配，内存，带宽流量也都非常充裕
- digitalocean 看样子也很靠谱，最低配应该很便宜，不过相信内存对于 rails 项目来说可能有些紧张，没用过。

**Comment by limingth** [comment]
超级期待，Come on!

**Comment by happypeter** [comment]
@limingth 好，我提上最高日程，下周一就在 happycasts.net 发出来，如果有个别情况最晚再拖一周。

**Comment by happypeter** [comment]
done

**Comment by limingth** [comment]
我看了一遍，讲的不错，好像没有讲 linode 啊

2013/12/9 Peter Wang notifications@github.com

**Comment by happypeter** [comment]
@limingth 其实视频里提了一句：“digitalocean 网站上的所有操作在 linode 都是一样的”

是啊，我讲课的节奏还是控制的不好，有些比较重要的地方却急匆匆的带过了，还是短练！

**Comment by limingth** [comment]
讲的很不错了，这么短时间覆盖那么多内容，我录过视频，知道其中的艰辛。

在 2013年12月11日下午4:41，Peter Wang notifications@github.com写道：
